// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mipkffoyktkojwpntlur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pcGtmZm95a3Rrb2p3cG50bHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NzE4OTksImV4cCI6MjA4NzU0Nzg5OX0.KUHm-c_TU6DH7p3ngZWbEPmQDwLSypG3jtF2pW-cpDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});